### ISSUE TITLE
Unable to connect Error 5003

### ISSUE THREAD

**Issue by mzaifquraishi** [mieszko4/react-native-zoom-us-test#12]
"Make sure you are connected to internet and your connection to zoom is not blocked by firewall or proxy. Error (5003)"

Please help me out on createing meeting.

**Comment by mieszko4** [comment]
Please provide more details. Android/ios emulator/real device, etc.

**Comment by mzaifquraishi** [comment]
sorry false issue, resolved it and added some more features to the plugin.
btw thanks
