### ISSUE TITLE
App crashes on meeting start

### ISSUE THREAD

**Issue by mzaifquraishi** [mieszko4/react-native-zoom-us-test#18]
hello i'm using the plugin with some more dependencies and its creaching.   

    `"react": "16.13.1",
    "react-native": "0.63.3",
    "react-native-zoom-us": "5.5",
    "@expo/vector-icons": "^12.0.0",
    "@react-native-community/async-storage": "^1.12.1",
    "@react-native-community/masked-view": "0.1.10",
    "@react-navigation/bottom-tabs": "^5.11.9",
    "@react-navigation/compat": "~5.1.25",
    "@react-navigation/drawer": "5.12.4",
    "@react-navigation/native": "5.9.3",
    "@react-navigation/stack": "5.14.3",
    "react-native-datepicker": "^1.7.2",
    "react-native-paper": "^4.7.2",
    "react-native-reanimated": "~1.13.0",
    "react-native-screens": "~2.15.2",
    "react-redux": "^7.2.3"`
i dont understand why it crashes with these plugin, i tried testing one by one but no luck. Can u help ??

**Comment by mieszko4** [comment]
Does the test app work for you? https://github.com/mieszko4/react-native-zoom-us-test

If you are using expo have you ejected it?

Paste error log please for starters.

**Comment by mzaifquraishi** [comment]
Sorry resolved with correct JWT. the error code it shows is 99 that means not supported on your device but it does after updating JWT token. btw Thanks
