### ISSUE TITLE
Error on ZoomUs.joinMeeting: "[Error: Error: 4, internalErrorCode=0]"

### ISSUE THREAD

**Issue by Alessandro1918** [mieszko4/react-native-zoom-us-test#27]
I'm getting this error when trying to join an already started meeting (by me, on my pc). 
It seems I can initialize the sdk, and get the event log "MEETING_STATUS_CONNECTING" right after pressing the "Join Example Meeting" button. I input the meeting password (and it's doing a validation - trying to enter the wrong password prompts me an "wrong password" message). Right after I press "Ok" on the password, I get his error logs:

 LOG  {"event": "success", "status": "MEETING_STATUS_DISCONNECTING"}
 LOG  {"event": "endedBySelf", "status": undefined}
 LOG  {"event": "meetingClientIncompatible", "status": "MEETING_STATUS_FAILED"}
 ERROR  [Error: Error: 4, internalErrorCode=0]
 LOG  {"event": "success", "status": "MEETING_STATUS_IDLE"}

I didn't do any changes from the code at https://github.com/mieszko4/react-native-zoom-us-test other than add my "skdKey", "sdkSecret", and my personal meetingID.

Any clues on why this is happening? 

Thanks in advance

![Sem título](https://user-images.githubusercontent.com/54996931/129267088-ca8fa56f-e964-4305-8854-a670ed576d2f.png)

**Comment by mieszko4** [comment]
@Alessandro1918 Have you modified `const exampleJoinLink = 'https://us02web.zoom.us/j/MEETING_NUMBER?pwd=PASSWORD';` with the real meeting link?

**Comment by mieszko4** [comment]
Also you can check with new version. Feel free to reopen

**Comment by Alessandro1918** [comment]
> 
> 
> @Alessandro1918 Have you modified `const exampleJoinLink = 'https://us02web.zoom.us/j/MEETING_NUMBER?pwd=PASSWORD';` with the real meeting link?

Yes, I used my own meeting number and password. 
I hit pause on that project so I won´t check those fixes for a while... But thanks for the update and follow-up!

**Comment by AnujSoni2208** [comment]
i am facing the same issue,
can anyone suggest me to solve it

![Screenshot 2022-08-10 at 10 48 07 AM](https://user-images.githubusercontent.com/79684672/183821566-7c77ec5e-3a53-484a-8946-790289b4dc4e.png)

**Comment by mieszko4** [comment]
That's interesting. Right before the ERROR there is `meetingClientIncompatible`. Are you joining a meeting or starting a new one?

**Comment by AnujSoni2208** [comment]
@mieszko4 
i am receiving meeting ID and Password, 
the meeting ID and Password in correct, i checked with other zoom app,

I am trying to joining a meeting,
but until the host is not joined it should show waiting,

actually it is working on IOS simulator but this issue is occurring on android

**Comment by AnujSoni2208** [comment]
> That's interesting. Right before the ERROR there is `meetingClientIncompatible`. Are you joining a meeting or starting a new one?

i created separate meeting link , id and password, and trying to join by app
but unable to join as you see logs like
1-) It is connecting then automatically getting disconnect

it is working fine on IOS Simulator but this error is occurring on android Emulator.

Can you suggest any solution  ?

**Comment by mieszko4** [comment]
Not sure what is the cause. I think we should upgrade Zoom SDK for Android.

**Comment by dishantjaykasodhan-kiwi** [comment]
did u guys get any solution ?

**Comment by AnujSoni2208** [comment]
> 

not yet

**Comment by mieszko4** [comment]
Is this still an issue? Please try with newest `6.16.5`.

**Comment by smikheiev** [comment]
> Is this still an issue? Please try with newest `6.16.5`.

@mieszko4 we started to have this error too out of blue with version `6.15.1`. interesting thing is that everything was working fine, and then at some point it got broken, and we didn't make any changes connected to zoom or video at all.
updating to `6.16.5` seems to fix the issue

**Comment by tommi97** [comment]
In some Android devices I have the same error when i try to join or start a meeting, with both version 6.15.1 and 6.16.5.
IOS work fine.

How can i resolve this issue in Android?

**Comment by poojabisht2202** [comment]
I am facing the same error even after version update to latest version but it doesn't seem to work. 
Any other solution ?

**Comment by RakshithCodewave** [comment]
[Error: Error: 4, internalErrorCode=0]
I'm getting same issue even after upgrading to latest SDK.
I'm attaching logs.

<img width="825" alt="Screenshot 2023-05-15 at 2 19 53 PM" src="https://github.com/mieszko4/react-native-zoom-us-test/assets/88820939/35c88fec-59f3-4969-8d5e-5ff2a8ddf303">

**Comment by Savan-ITDEV** [comment]
Does this issue have a solution?

**Comment by RakshithCodewave** [comment]
@Savan-ITDEV this issue is with old SDK, Please use latest android SDK to resolve this issue.

**Comment by tommi97** [comment]
> Does this issue have a solution?

Read [this comment](https://github.com/mieszko4/react-native-zoom-us-test/issues/66#issuecomment-1564072606)

**Comment by Savan-ITDEV** [comment]
Could you suggest how to integrate React Native Project? thank for support

**Comment by mieszko4** [comment]
> @Savan-ITDEV this issue is with old SDK, Please use latest android SDK to resolve this issue.

I created issue to upgrade Android SDK (https://github.com/mieszko4/react-native-zoom-us/issues/280)
