### ISSUE TITLE
are you going to upgrade this to latest version?

### ISSUE THREAD

**Issue by YashMistry** [mieszko4/react-native-zoom-us-test#5]

**Comment by mieszko4** [comment]
I am sorry I have no time to do it now.
But yes, I want to start from scratch to use rn60

**Comment by shashika77** [comment]
Can you make plugin for native Cordova **_(*Not for ionic)_**

**Comment by mieszko4** [comment]
> Can you make plugin for native Cordova **_(*Not for ionic)_**

Isn't Cordova simply web wrapper? I do not have plan to build native Cordova plugin. I suggest you try to use the existing https://marketplace.zoom.us/docs/sdk/video/web

**Comment by mieszko4** [comment]
It's updated now

**Comment by mieszko4** [comment]
> Can you make plugin for native Cordova **_(*Not for ionic)_**

that looks like a totally new project to me :)
