### ISSUE TITLE
Execution failed for task ':react-native-zoom-us:compileDebugJavaWithJavac'

### ISSUE THREAD

**Issue by shafqatbari** [mieszko4/react-native-zoom-us-test#62]
I cloned the Project I am facing issue to run this

I have done gradle clean but its not working.

`
/Users/shafqatbari/Downloads/react-native-zoom-us-test-master/node_modules/react-native-zoom-us/android/src/main/java/ch/milosz/reactnative/RNZoomUsModule.java:374: error: cannot find symbol
          if (joinMeetingResult != MeetingError.MEETING_ERROR_SUCCESS) {
                                   ^
  symbol: variable MeetingError
Note: /Users/shafqatbari/Downloads/react-native-zoom-us-test-master/node_modules/react-native-zoom-us/android/src/main/java/ch/milosz/reactnative/RNZoomUsModule.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
100 errors

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':react-native-zoom-us:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.`

**Comment by mieszko4** [comment]
Please try with newest `6.16.5` (I just updated test app)

**Comment by shafqatbari** [comment]
@mieszko4 Thanks its working
