### ISSUE TITLE
Join meeting crashes the app android

### ISSUE THREAD

**Issue by paingpyaethu** [mieszko4/react-native-zoom-us-test#65]
it works now.. i'm using version 6.16.4. but can't build assembleRelease. is any other solution? or how to fix app crash problem in latest version please.

**Comment by amdrade** [comment]
Error on Android 12

`java_vm_ext.cc:579] JNI DETECTED ERROR IN APPLICATION: JNI CallIntMethodV called with pending exception java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__emutls_get_address" referenced by "/data/app/~~e9qXucHVzLd-A--tsVnimg==/com.zoomustest-TxucE_Q6X_njAg151v2UyA==/lib/x86_64/libannotate.so"...
java_vm_ext.cc:579]   at void java.lang.Runtime.loadLibrary0(java.lang.ClassLoader, java.lang.Class, java.lang.String) (Runtime.java:1077)
java_vm_ext.cc:579]   at void java.lang.Runtime.loadLibrary0(java.lang.Class, java.lang.String) (Runtime.java:998)
java_vm_ext.cc:579]   at void java.lang.System.loadLibrary(java.lang.String) (System.java:1656)
java_vm_ext.cc:579]   at void com.zipow.videobox.mainboard.module.ZmSdkMainBoard.loadSDKConfAppNativeModules() (ZmSdkMainBoard.java:8)
java_vm_ext.cc:579]   at void com.zipow.videobox.mainboard.module.ZmSdkMainBoard.createConfAppForSdk(java.lang.String) (ZmSdkMainBoard.java:8)
java_vm_ext.cc:579]   at void com.zipow.videobox.VideoBoxApplication.initConfAppForSDK(java.lang.String) (VideoBoxApplication.java:23)
java_vm_ext.cc:579]   at int com.zipow.videobox.VideoBoxApplication.startConfServiceForSDK(android.os.Bundle) (VideoBoxApplication.java:8)
java_vm_ext.cc:579]   at int com.zipow.videobox.ptapp.ConfProcessMgr.createConfProcess(java.lang.String) (ConfProcessMgr.java:15)
java_vm_ext.cc:579]   at void com.zipow.videobox.mainboard.Mainboard.notifyUrlActionImpl(java.lang.String) (Mainboard.java:-2)
java_vm_ext.cc:579]   at void com.zipow.videobox.mainboard.Mainboard.notifyUrlAction(java.lang.String) (Mainboard.java:6)
java_vm_ext.cc:579]   at int com.zipow.videobox.confapp.meeting.premeeting.joinscene.ZMWebStart.startConfrence(android.content.Context) (ZMWebStart.java:36)
java_vm_ext.cc:579]   at boolean com.zipow.videobox.JoinByURLActivity.g(android.net.Uri) (JoinByURLActivity.java:4)
java_vm_ext.cc:579]   at boolean com.zipow.videobox.JoinByURLActivity.a(android.net.Uri, boolean, boolean) (JoinByURLActivity.java:39)
java_vm_ext.cc:579]   at void com.zipow.videobox.JoinByURLActivity.b(android.net.Uri, boolean) (JoinByURLActivity.java:16)
java_vm_ext.cc:579]   at void com.zipow.videobox.JoinByURLActivity.onResume() (JoinByURLActivity.java:181)
java_vm_ext.cc:579]   at void android.app.Instrumentation.callActivityOnResume(android.app.Activity) (Instrumentation.java:1476)
java_vm_ext.cc:579]   at void android.app.Activity.performResume(boolean, java.lang.String) (Activity.java:8191)
java_vm_ext.cc:579]   at boolean android.app.ActivityThread.performResumeActivity(android.app.ActivityThread$ActivityClientRecord, boolean, java.lang.String) (ActivityThread.java:4747)
java_vm_ext.cc:579]   at void android.app.ActivityThread.handleResumeActivity(android.app.ActivityThread$ActivityClientRecord, boolean, boolean, java.lang.String) (ActivityThread.java:4790)
java_vm_ext.cc:579]   at void android.app.servertransaction.ResumeActivityItem.execute(android.app.ClientTransactionHandler, android.app.ActivityThread$ActivityClientRecord, android.app.servertransaction.PendingTransactionActions) (ResumeActivityItem.java:54)
java_vm_ext.cc:579]   at void android.app.servertransaction.ActivityTransactionItem.execute(android.app.ClientTransactionHandler, android.os.IBinder, android.app.servertransaction.PendingTransactionActions) (ActivityTransactionItem.java:45)
java_vm_ext.cc:579]   at void android.app.servertransaction.TransactionExecutor.executeLifecycleState(android.app.servertransaction.ClientTransaction) (TransactionExecutor.java:176)
java_vm_ext.cc:579]   at void android.app.servertransaction.TransactionExecutor.execute(android.app.servertransaction.ClientTransaction) (TransactionExecutor.java:97)
java_vm_ext.cc:579]   at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:2210)
java_vm_ext.cc:579]   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:106)`

**Comment by Avais0af** [comment]
I am also facing the same issue, any help would be appreciated @mieszko4

**Comment by khuongphp** [comment]
Pls upgrade your react-native version to ^0.71.3
It worked on my case

**Comment by amdrade** [comment]
Don't work on xiaomi Android 12 for me :(

**Comment by mieszko4** [comment]
I created issue to upgrade Android SDK (https://github.com/mieszko4/react-native-zoom-us/issues/280)

**Comment by mieszko4** [comment]
Test app works now with Android 13 so should also work with Android 12 - it uses react-native-zoom-us@6.18.9.

**Comment by mieszko4** [comment]
New issue created -> https://github.com/mieszko4/react-native-zoom-us/issues/358
