### ISSUE TITLE
How to use find if the call is ended. Is there any event or method which tells the call is ended?

### ISSUE THREAD

**Issue by kumarutsav111** [mieszko4/react-native-zoom-us-test#7]
How to use find if the call is ended. Is there any event or method which tells the call is ended? Please help. Thanks in advance.
await ZoomUs.startMeeting(
                name,///
                providerZoomId2,//this.meetingNo,//
                userId2,
                userType2,
                zoomAccessToken2,
                zoomToken2
            ).then(results => {
            });

**Comment by mieszko4** [comment]
I am not sure, I need to take some time to rewrite this whole lib bridge.

**Comment by kumarutsav111** [comment]
Thanks @mieszko4 . That would be very helpful, please add it.

**Comment by mieszko4** [comment]
There are now events that you can use to check if call has ended.
